name: _deployment
on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      branch:
        required: true
        type: string
      url:
        required: false
        type: string
      user:
        required: false
        type: string
    secrets:
      deploy_token:
        required: true

jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: echo
        run: |
          echo "Deploying to ${{ inputs.branch }}"