name: Run
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'preprod'
        type: choice
        options:
          - preprod
          - prod
          - prod2

jobs:
  print-tag:
    runs-on: ubuntu-latest
    if: environment == 'preprod'
    steps:
      - name: Deploy Preprod
        run: echo "Deploy Preprod"
      - uses: ./.github/workflows/push-rtm.yml
