name: ":arrow_forward: Run "
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'preprod'
        type: choice
        options:
          - preprod
          - prod
          - prod2

jobs:
  deploy-preprod:
    if: inputs.environment == 'preprod'
    uses: ./.github/workflows/push-rtm.yml

  deploy-prod:
    if: inputs.environment == 'prod'
    uses: ./.github/workflows/push-master.yml
